from app import app, db, Maestro


MAESTROS = [
    ("DR. INOCENTE MELITÓN GARCÍA", "DIRECCION"),
    ("DRA. MARIANA LÓPEZ VICTORIANO", "SUBDIRECCION ACADEMICA"),
    ("MTRO. BELBL ÁNGEL ÁNGELES REYES", "SUBDIRECCION ADMINISTRATIVA"),
    ("LIC. YADIRA ALMANZA GONZÁLEZ", "UPSE"),
    ("DRA. FABIOLA LIZBETH ARIAS HINOJOSA", "CONTROL ESCOLAR"),
    ("MTRO. ELADIO CEDILLO GONZÁLEZ", "RECURSOS MATERIALES"),
    ("DRA. EMMA GARCÍA PEDROZA", "RECURSOS HUMANOS"),
    ("MTRO. SERGIO GONZÁLEZ ISIDRO", "POSGRADO"),
    ("MTRA. ROSA LIDIA MERCADO TÉLLEZ", "PROMOCION Y DIVULGACION CULTURAL"),
    ("MTRO. PAVEL ALEXIS SIERRA TAPIA", "FORMACION INICIAL"),
    ("MTRO. CARLOS FERNANDO TÉLLEZ CALDERÓN", "SAF"),
    ("MTRA. AURORA ESTEFANÍA AVIÑA BRAVO", "SEGUIMIENTO A PLANES Y PROGRAMAS DE ESTUDIOS"),
    ("MTRO. ISRAEL CRUZ MARTÍNEZ", "CONTROL ESCOLAR"),
    ("MTRO. ALAN JOSSUÉ GARCÍA ACUÑA", "RECURSOS MATERIALES"),
    ("LIC. SERGIO GARCÍA CORRAL", "RECURSOS MATERIALES"),
    ("DR. ALEJANDRO GARCÍA OAXACA", "INVESTIGACION E INNOVACION"),
    ("DR. JANUARIO VÍCTOR MANUEL GARDUNO BASTIDA", "INVESTIGACION E INNOVACION"),
    ("LIC. JORGE GIL CONTRERAS", "RECURSOS HUMANOS"),
    ("LIC. PEDRO GÓMEZ CONZUELO", "FORMACION INICIAL"),
    ("MTRO. ABRAHAM GONZAGA VALENCIA", "PROMOCION Y DIVULGACION CULTURAL"),
    ("MTRA. CITLALLI LÓPEZ CRUZ", "RECURSOS FINANCIEROS"),
    ("MTRO. MARCO ANTONIO LÓPEZ OCTAVIANO", "VINCULACION"),
    ("MTRA. ALICIA ESTHELA MELCHOR DURÁN", "UPSE"),
    ("MTRA. MARÍA DEL CARMEN MONDRAGÓN FLORES", "SEGUIMIENTO A PLANES Y PROGRAMAS DE ESTUDIOS"),
    ("LIC. ISABEL MONROY PLATA", "DESARROLLO DOCENTE"),
    ("MTRA. JACQUELINE SALAZAR GARCÍA", "FORMACION INICIAL"),
    ("MTRO. JULIO CÉSAR TOVAR HERNÁNDEZ", "PROMOCION Y DIVULGACION CULTURAL"),
    ("LIC. KARINA VANESSA VELÁZQUEZ RODRÍGUEZ", "UPSE"),
    ("MTRA. JANNETH LOZANO REYES", "FORMACION INICIAL"),
    ("LIC. CARLOS GUSTAVO CORTÉS QUIJADA", "RECURSOS HUMANOS"),
    ("MTRA. YASLIN YATSIDI FLORES ORDÓÑEZ", "HORAS CLASE"),
    ("DR. EDGAR MATÍNEZ GARDUÑO", "HORAS CLASE"),
    ("MTRO. RAÍ YAEL MIRANDA SALGADO", "HORAS CLASE"),
    ("MTRO. OMAR NAVARRETE MONTES DE OCA", "VINCULACION"),
    ("LIC. JESSIA TAVIRA ORTÍZ", "PROMOCION Y DIVULGACION CULTURAL"),
    ("MTRA. MARÍA FERNANDA ZÁRATE HENDERSON", "PROMOCION Y DIVULGACION CULTURAL"),
    ("LIC. GLORIA IVONNE ALBARRÁN ENCISO", "POSGRADO"),
    ("LIC. ANAYELI AMBROCIO GARCÍA", "RECURSOS FINANCIEROS"),
    ("LIC. MAYCA SURISADDAY CÁRDENAS DE LA LUZ", "HORAS CLASE"),
    ("DR. LUIS JAVIER DÍAZ CASTILLO", "HORAS CLASE"),
    ("MTRA. SARAÍ FELISA DIONICIO GARCÍA", "HORAS CLASE"),
    ("LIC. ELIBERTH RUTH FLORES MERCADO", "HORAS CLASE"),
    ("MTRO. MANUEL ANTONIO FLORES MERCADO", "HORAS CLASE"),
    ("MTRA. FELIPA GALVÁN JUÁREZ", "ARCHIVO"),
    ("DRA. ELIZABETH GÁRFIAS SUÁREZ", "HORAS CLASE"),
    ("LIC. IRMA LIZETH GUERRA GONZÁLEZ", "HORAS CLASE"),
    ("LIC. SARAHÍ HERNÁNDEZ FLORES", "HORAS CLASE"),
    ("MTRA. IVVONE ITZEL HERNÁNDEZ MARTÍNEZ", "HORAS CLASE"),
    ("LIC. AMANCIO LÓPEZ IBARRA", "HORAS CLASE"),
    ("LIC. DANIELA YURIDIANA MEJÍA CORTÉS", "HORAS CLASE"),
    ("LIC. GERARDO DE JESÚS RODRÍGUEZ MARTÍNEZ", "HORAS CLASE"),
    ("LIC. JAZMÍN RODRÍGUEZ ORTUÑO", "HORAS CLASE"),
    ("LIC. JAQUELINE SÁNCHEZ VICTORIA", "HORAS CLASE"),
    ("ISAURA LOPEZ OCTAVIANO", "AREA SECRETARIAL"),
    ("MA. DEL CARMEN VENTURA MENDOZA", "AREA SECRETARIAL"),
    ("RUTH HELENA ALVAREZ BAYONA", "AREA SECRETARIAL"),
    ("DOLORES SANDOVAL MARTINEZ", "AREA SECRETARIAL"),
    ("ROSA GONZÁLEZ GONZÁLEZ", "RECURSOS MATERIALES"),
    ("OMAR BASTIDA OVANDO", "RECURSOS MATERIALES"),
    ("JORGE FLORES OVANDO", "RECURSOS MATERIALES"),
    ("MARCOS JHOAN GÁLVEZ GUADARRAMA", "RECURSOS MATERIALES"),
    ("ALEJANDRO GARCÍA HERNÁNDEZ", "RECURSOS MATERIALES"),
    ("JESÚS ROMERO OJEDA", "RECURSOS MATERIALES"),
    ("VÍCTOR MANUEL MARTÍNEZ RAMÍREZ", "RECURSOS MATERIALES"),
    ("RUFINA OVANDO VÁLDEZ", "RECURSOS MATERIALES"),
    ("ANTONIO SALINAS SIMÓN", "RECURSOS MATERIALES"),
]


def main():
    with app.app_context():
        db.create_all()

        creados = 0
        actualizados = 0

        for nombre, area in MAESTROS:
            nombre = (nombre or "").strip()
            area = (area or "").strip() or None
            if not nombre:
                continue

            m = Maestro.query.filter_by(nombre=nombre).first()
            if m:
                if area and (not m.area):
                    m.area = area
                    actualizados += 1
            else:
                m = Maestro(nombre=nombre, area=area)
                db.session.add(m)
                creados += 1

        db.session.commit()
        print(f"Maestros creados: {creados}")
        print(f"Maestros actualizados: {actualizados}")


if __name__ == "__main__":
    main()

